### ISSUE TITLE
2주차 복습문제 2-4

### ISSUE THREAD

**Issue by jyun0618** [gah508/EPOCH_Beginner#2]
# 🤔질문 사항🤔
> *2주차 복습문제 2-4*
> (4) 주식 가격이 $105 이상이고 거래량이 300 미만인 경우, 거래량을 350으로 대체하고 그 데이터를 필터링하세요.
---

## ❓질문 사항
> 제 풀이는 이러한데.. 조건은 어떻게 표현할 지 알겠는데 350으로 값을 대체하는 함수로 어떤 함수를 써야할지 잘 모르겠습니다..! 여러분들의 풀이가 궁금해요
```
def volume_filter(df):
   df.loc[(df['Price'] >= 105) & (df['Volume'] < 300)]
   return df['Volume'] == 350

result = volume_filter(df)
print(result)
```
이것은 출력 결과입니다
```
Date
2024-01-01    False
2024-01-02    False
2024-01-03    False
2024-01-04    False
2024-01-05    False
Name: Volume, dtype: bool
```

## ❗답변
> *멤버들의 질문을 보고 해결할 수 있는 질문인 경우 답변을 작성해주세요.*

**Comment by Y1OO5B** [comment]
저도 지윤님과 같은 방식으로 값을 350으로 변환했다가 오류가 났었는데요...!
저희의 방식이 잘못된 거라기보다는 문제 오류인 것 같아여!!!
원본 데이터를 보면 조건에 부합하는 행이 없거든요..
![다운로드](https://github.com/user-attachments/assets/39277cbf-39df-4c05-8eff-10d72ddac791)

이 문제를 해결하기 위해 문장을 여러가지로 생각해볼 수 있는데
[원문제] (4) 주식 가격이 $105 이상이고 거래량이 300 미만인 경우, 거래량을 350으로 대체하고 그 데이터를 필터링하세요.
[수정1] (4) 주식 가격이 $105 이상 **_이거나_**  거래량이 300 미만인 경우, 거래량을 350으로 대체하고 그 데이터를 필터링하세요.
[수정2] (4) 주식 가격이 $105 이상이고 거래량이 300 **_이하_** 인 경우, 거래량을 350으로 대체하고 그 데이터를 필터링하세요.

저는 [수정1]의 경우는 귀찮을 거 같아서 [수정2]를 임의로 가정하고 문제를 풀었습니다.. ㅎㅎ
![image](https://github.com/user-attachments/assets/c8fdf5df-5bb7-482c-8a09-43ee65e3f55b)

**Comment by jyun0618** [comment]
왕 친절한 설명 감사합니다아
